import React from 'react';
import { IoIosArrowBack } from 'react-icons/io';

const WritingArea = () => {
    const messages: { id: number, message: string }[] = [
        { id: 1, message: "As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike." },
        { id: 2, message: "As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike." },
        { id: 3, message: "As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike." },

    ]
    return (
        <section>
            <div className='row'>
                <div className='col-12 col-lg-7'>
                    <p>Enter input to get <span className='text-primary text-opacity-75'>Writing Assistant</span></p>
                    <div className='d-flex'>
                        <div>
                            <label htmlFor="count">Words Count: </label>
                            <input type="number" defaultValue={0} name="" id="count" />
                        </div>
                        <div className='d-flex align-items-center mx-5'>
                            <label htmlFor="prompt">Prompt:</label>
                            <select className="form-select ms-2" aria-label="Default select example" id='prompt'>
                                <option selected>Select</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                        <div className='d-flex align-items-center'>
                            <label htmlFor="prompt">Creativity:</label>
                            <select className="form-select ms-2" aria-label="Default select example" id='prompt'>
                                <option selected>Select</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                    </div>

                    <div>

                        <textarea className='border border-0 shadow w-100' name="" id="" rows={20}></textarea>
                    </div>

                </div>
                <div className='d-none d-lg-flex flex-column justify-items-center align-items-center col-lg-1 min-vh-100 mt-5'>
                    <div>
                        <div className='vr' style={{ height: "120px" }}></div>
                    </div>
                    <div><IoIosArrowBack className='fs-3 border rounded-circle p-1' /></div>
                    <div className='h-50'>
                        <div className='vr h-100'></div>
                    </div>
                </div>
                <div className='col-12 col-lg-4'>
                    <div className='d-flex justify-content-center mt-5'>
                        <button className='border border-0 px-5 py-2 bg-primary text-white'>Write for me</button>
                    </div>
                    <div className=''>
                        <p className='text-end text-warning display-none display-lg-block'>clear</p>
                        {
                            messages.map(m => <div key={m.id} className='d-flex align-items-center shadow pt-2 mb-3'>
                                <p className=''><button className='btn btn-white text-primary'>copy</button></p>
                                <p className='border-start border-{#707070} ps-3 fst-normal lh-1'>{m.message}</p>
                            </div>)
                        }
                    </div>
                </div>
            </div>
        </section>
    );
};

export default WritingArea;